version: '3'
services:
    ilias:
        image: srsolutions/ilias
        ports:
          - 8080:80
        links:
          - mysql
        volumes:
          - ${HOST_PWD}:/var/www/html
        environment:
          - ILIAS_AUTO_SETUP=1
          - ILIAS_DB_USER=root
          - ILIAS_DB_PASSWORD=example
          - ILIAS_ROOT_PASSWORD=example
          - ILIAS_DEVMODE=1
    mysql:
        image: mysql:5.7
        ports:
          - 3307:3306
        command: |
            --character-set-server=utf8
            --collation-server=utf8_general_ci
            --max-allowed-packet=32M
            --default_authentication_plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=example
          - MYSQL_DATABASE=ilias